server:
  #为此注册中心的访问的端口
  port: 10010
spring:
  application:
    #注册中心的名字，有字母和数字组成，不同的注册中心名字不能重复
    name: EurekaServer1
eureka:
  #客户端
  client:
    service-url:
      #注册到注册中心的路径（可以自己注册自己）
      defaultZone: http://127.0.0.1:10010/eureka
    #允许注册中心自己注册自己
    register-with-eureka: true